### PR TITLE
Generic Owner Label Name

### PR DESCRIPTION
**Pull request by CpuID**
Make the owner label name more generic.

Discussion in https://github.com/buildkite/sockguard/pull/11 (abandoned PR).

### CODE REVIEW

**Comment by lox** [comment]
FWIW, I was following the guidelines at https://docs.docker.com/config/labels-custom-metadata/, specifically:

> Authors of third-party tools should prefix each label key with the reverse DNS notation of a domain they own, such as com.example.some-label.

**Comment by CpuID** [comment]
> FWIW, I was following the guidelines at https://docs.docker.com/config/labels-custom-metadata/, specifically:

I actually normally follow exactly the same guidance at $dayjob for all internal labels of resources :) Agree with you there, in most cases.

I definitely still think the `sockguard.owner` format feels more generic in this instance, but I am torn between best practices vs the fact that label needs to be propagated in various non-buildkite places for open source use :)

**Comment by lox** [comment]
It's a tricky one! I think we'd prefer to keep our name in there after some thought. We contribute back all of our tools as open-source for use in any CI system, and we maintain, support and audit them. Reckon it's not a huge ask to have our company name mentioned in a label, especially given it's following the recommendations outlined by Docker.

Is there a compelling reason to remove it beyond aesthetics?

**Comment by CpuID** [comment]
> Is there a compelling reason to remove it beyond aesthetics?

not really, tbh. I'll likely just keep running a fork with this branch included instead :)

**Comment by lox** [comment]
> not really, tbh. I'll likely just keep running a fork with this branch included instead :)

Open-source FTW :)

**Comment by CpuID** [comment]
> It's a tricky one! I think we'd prefer to keep our name in there after some thought. We contribute back all of our tools as open-source for use in any CI system, and we maintain, support and audit them. Reckon it's not a huge ask to have our company name mentioned in a label, especially given it's following the recommendations outlined by Docker.

Fair call, I generally like to try and see company names skipped from open source tooling where possible (other than credits in READMEs and such). I also find more popular projects go and get their own GH org over time to allow the projects to gain more independence, not suggesting that for this project (small utility, doesn't justify it).

**Comment by lox** [comment]
> Fair call, I generally like to try and see company names skipped from open source tooling where possible (other than credits in READMEs and such). I also find more popular projects go and get their own GH org over time to allow the projects to gain more independence, not suggesting that for this project (small utility, doesn't justify it).

I think if you remove all incentive for for-profit companies to participate in open-source you reduce the pool of high quality open-source software. But yeah, I hear ya.

**Comment by CpuID** [comment]
> I think if you remove all incentive for for-profit companies to participate in open-source you reduce the pool of high quality open-source software. But yeah, I hear ya.

+1 yep it's definitely a grey area :)

**Pull request closed without merging**
