### PR TITLE
Add minimal socket proxy tests

### PR DESCRIPTION
**Pull request by lox**
A very minimal test for the socket proxy.

### CODE REVIEW

**Comment by CpuID** [comment]
@lox curious - is it possible to make the test results public for open source repos...?

**Comment by lox** [comment]
It's something we are actively working on, but for now, shall I invite you to the Buildkite project?

**Comment by CpuID** [comment]
> It's something we are actively working on, but for now, shall I invite you to the Buildkite project?

sure :)

**Comment by CpuID** [comment]
> Check now, every time I forget to add the pipeline to the team

works now thx

**Pull request merged**
